version: '2'
services:
  preview:
    build: .
    command: serve --watch --host=0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./:/site

  jekyll:
    build: .
    volumes:
      - ./:/site
